import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { render, screen, fireEvent, cleanup, waitFor, within } from "@solidjs/testing-library";
import type { ServiceResult } from "../../../bridge/types";

// Mock the bridge invoke layer (no Tauri runtime in tests) so we can assert
// WHICH existing memory_* command each control triggers.
vi.mock("../../../bridge/invoke", () => ({
  bridgeInvoke: vi.fn(),
  bridgeInvokeOptional: vi.fn(async () => null),
}));

import { CognitionPanel } from "./CognitionPanel";
import { memoryStore, converseStore } from "../../../stores";
import { bridgeInvoke } from "../../../bridge/invoke";

const mockInvoke = bridgeInvoke as unknown as ReturnType<typeof vi.fn>;

function ok<T>(data: T): ServiceResult<T> {
  return { ok: true, data };
}
function fail(message = "boom"): ServiceResult<never> {
  return { ok: false, code: "error", message } as ServiceResult<never>;
}

describe("CognitionPanel (task 6.3, Req 5.6)", () => {
  beforeEach(() => {
    mockInvoke.mockReset();
    mockInvoke.mockResolvedValue(ok(0));
    memoryStore.seedCognitionResults([]);
    memoryStore.seedCognitionRunning([]);
    converseStore.setActiveThread(null);
  });
  afterEach(() => cleanup());

  it("renders a labelled control for each of the six cognition jobs", () => {
    render(() => <CognitionPanel />);
    for (const name of [
      "Run Reflect",
      "Run Dream",
      "Run Consolidate",
      "Run Active learning",
      "Run Self-improvement",
      "Run Entity extraction",
    ]) {
      expect(screen.getByRole("button", { name })).toBeInTheDocument();
    }
  });

  it("triggers the correct existing command for a control", async () => {
    mockInvoke.mockResolvedValueOnce(ok(2));
    render(() => <CognitionPanel />);
    fireEvent.click(screen.getByRole("button", { name: "Run Reflect" }));
    await waitFor(() => expect(mockInvoke).toHaveBeenCalledWith("memory_reflect", undefined));
  });

  it("renders a PERSISTENT result panel showing what changed (not a toast)", async () => {
    mockInvoke.mockResolvedValueOnce(ok({ processed: 8, entities_linked: 3 }));
    render(() => <CognitionPanel />);
    fireEvent.click(screen.getByRole("button", { name: "Run Entity extraction" }));

    // The result panel (a region) shows the concrete changes and persists.
    const region = screen.getByRole("region", { name: "Cognition results" });
    expect(await screen.findByText("Memories processed")).toBeInTheDocument();
    expect(within(region).getByText("Entities linked")).toBeInTheDocument();
    expect(within(region).getByText("8")).toBeInTheDocument();
    expect(within(region).getByText("3")).toBeInTheDocument();
    expect(within(region).getByLabelText("AI-authored by KRIA")).toHaveTextContent(
      "Generated by KRIA",
    );
  });

  it("reflects the running state while a job is in-flight", async () => {
    let resolveRun: (() => void) | undefined;
    mockInvoke.mockImplementationOnce(
      () =>
        new Promise<ServiceResult<number>>((resolve) => {
          resolveRun = () => resolve(ok(1));
        }),
    );
    render(() => <CognitionPanel />);
    const btn = screen.getByRole("button", { name: "Run Reflect" });
    fireEvent.click(btn);

    // While running: the job shows a progress indicator and the store reflects
    // the in-flight state (which drives the Core, Req 5.6).
    expect(await screen.findByRole("progressbar")).toBeInTheDocument();
    expect(memoryStore.isCognitionRunning("reflect")).toBe(true);

    // Always resolve so the in-flight job settles and never leaks.
    resolveRun?.();
    await waitFor(() => expect(screen.queryByRole("progressbar")).toBeNull());
    expect(memoryStore.isCognitionRunning("reflect")).toBe(false);
  });

  it("shows an honest failure in the result panel (never a silent no-op)", async () => {
    mockInvoke.mockResolvedValueOnce(fail("engine offline"));
    render(() => <CognitionPanel />);
    fireEvent.click(screen.getByRole("button", { name: "Run Reflect" }));
    expect(await screen.findByText(/engine offline/)).toBeInTheDocument();
    expect(screen.getByText("Failed")).toBeInTheDocument();
  });

  it("disables Consolidate with an honest note when no conversation is active", () => {
    render(() => <CognitionPanel />);
    expect(screen.getByRole("button", { name: "Run Consolidate" })).toBeDisabled();
    expect(
      screen.getByText("Open a conversation to consolidate its session."),
    ).toBeInTheDocument();
  });

  it("forwards the active conversation's session id to memory_consolidate", async () => {
    converseStore.setActiveThread("thread-42");
    mockInvoke.mockResolvedValueOnce(ok(4));
    render(() => <CognitionPanel />);
    const btn = screen.getByRole("button", { name: "Run Consolidate" });
    expect(btn).not.toBeDisabled();
    fireEvent.click(btn);
    await waitFor(() =>
      expect(mockInvoke).toHaveBeenCalledWith("memory_consolidate", { sessionId: "thread-42" }),
    );
  });
});
