//! Answer-from-system helpers for Catalog / Help / Explain / Recent-changes
//! (settings-nl-intelligence Wave 3). Everything here is derived from the schema
//! (`FieldMeta`, `all_fields`, env-lock, risk, valid_values) + the live config +
//! the audit ledger — NEVER from the LLM and NEVER hallucinated. No per-field
//! hardcoding: the catalog is generated by iterating the schema.

use std::collections::BTreeMap;

use crate::config::{is_secret_field, schema};

/// Human label for a field id (generic: `snake_case` → spaced words).
pub fn label(field: &str) -> String {
    field.replace('_', " ")
}

/// Human-friendly value rendering (bool → on/off, string as-is, else JSON).
pub fn render_value(v: &serde_json::Value) -> String {
    match v {
        serde_json::Value::String(s) => s.clone(),
        serde_json::Value::Bool(b) => (if *b { "on" } else { "off" }).to_string(),
        other => other.to_string(),
    }
}

pub fn requires_restart(m: &schema::FieldMeta) -> bool {
    !m.hot_reload && m.effect_kind == schema::EffectKind::None
}

/// Trailing note about restart / env-lock for a field (empty when neither).
pub fn status_note(section: &str, field: &str) -> String {
    let m = schema::field_meta(section, field);
    let mut notes = Vec::new();
    if let Some(var) = schema::env_lock_var(section, field) {
        if schema::is_env_locked(section, field) {
            notes.push(format!("locked by env {var}"));
        }
    }
    if requires_restart(&m) && m.prompt_changeable {
        notes.push("takes effect after restart".to_string());
    }
    if notes.is_empty() {
        String::new()
    } else {
        format!(" ({})", notes.join("; "))
    }
}

/// "What settings can I configure?" / "list <group> settings" — the prompt-
/// changeable, non-secret fields, grouped by section, with allowed values.
pub fn list_configurable(group: Option<&str>) -> String {
    let mut by_section: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (s, f) in schema::all_fields() {
        if let Some(g) = group {
            if s != g {
                continue;
            }
        }
        if is_secret_field(&s, &f) {
            continue;
        }
        let m = schema::field_meta(&s, &f);
        if !m.prompt_changeable {
            continue;
        }
        let allowed = m
            .valid_values
            .map(|v| format!(" [{}]", v.join("/")))
            .unwrap_or_default();
        by_section
            .entry(s.clone())
            .or_default()
            .push(format!("{}{}", label(&f), allowed));
    }
    if by_section.is_empty() {
        return match group {
            Some(g) => format!("I don't have prompt-changeable settings under \"{g}\"."),
            None => "No prompt-changeable settings are available.".to_string(),
        };
    }
    let head = match group {
        Some(g) => format!("Settings you can change under \"{g}\":"),
        None => "Here are the settings you can change:".to_string(),
    };
    let body = by_section
        .into_iter()
        .map(|(s, fields)| format!("• {s}: {}", fields.join(", ")))
        .collect::<Vec<_>>()
        .join("\n");
    format!("{head}\n{body}")
}

/// "Explain X" / "what does X do" / "what are valid values for X" / "why is X
/// locked" — everything known about one field, from schema + current value.
pub fn explain(section: &str, field: &str, root: &serde_json::Value) -> String {
    let m = schema::field_meta(section, field);
    let mut parts: Vec<String> = Vec::new();
    parts.push(format!(
        "{}.{} (risk: {})",
        section,
        field,
        format!("{:?}", m.risk).to_lowercase()
    ));
    if !is_secret_field(section, field) {
        if let Some(v) = root.get(section).and_then(|s| s.get(field)) {
            parts.push(format!("currently {}", render_value(v)));
        }
    } else {
        parts.push("secret (set/unset only)".to_string());
    }
    if let Some(vals) = m.valid_values {
        parts.push(format!("allowed: {}", vals.join(", ")));
    }
    if requires_restart(&m) && m.prompt_changeable {
        parts.push("requires restart".to_string());
    }
    if let Some(var) = schema::env_lock_var(section, field) {
        if schema::is_env_locked(section, field) {
            parts.push(format!("locked by env {var}"));
        }
    }
    if !m.prompt_changeable {
        parts.push("not changeable by prompt".to_string());
    }
    parts.join("; ")
}

/// "How do I change X?" — schema-generated instructions (no LLM).
pub fn help_change(section: &str, field: &str) -> String {
    let m = schema::field_meta(section, field);
    if !m.prompt_changeable {
        return format!(
            "{}.{} can't be changed from chat. {}",
            section,
            field,
            if is_secret_field(section, field) {
                "It's a secret — set it through the secure settings flow."
            } else {
                "It's managed by the system or requires a config file/restart."
            }
        );
    }
    let example = m.valid_values.and_then(|v| v.first().copied());
    let mut s = match example {
        Some(ex) => format!("Just tell me — e.g. \"set {} to {ex}\".", label(field)),
        None => format!("Just tell me — e.g. \"set {} to <value>\".", label(field)),
    };
    if let Some(vals) = m.valid_values {
        s.push_str(&format!(" Valid values: {}.", vals.join(", ")));
    }
    if m.risk != crate::safety::RiskLevel::Green {
        s.push_str(" I'll ask you to approve it first.");
    }
    if schema::is_env_locked(section, field) {
        if let Some(var) = schema::env_lock_var(section, field) {
            s.push_str(&format!(
                " Note: it's currently locked by environment variable {var}."
            ));
        }
    }
    if requires_restart(&m) {
        s.push_str(" It takes effect after a restart.");
    }
    s
}

/// "Which providers are available?" — the full provider CATALOG (schema-driven
/// from `ProviderType`), marking which are configured + which is active. No
/// per-provider hardcoding.
pub fn list_providers(cfg: &crate::llm::provider::config::ProvidersConfig) -> String {
    use crate::llm::provider::config::ProviderType;
    let mut lines = Vec::new();
    for pt in ProviderType::all() {
        let name = pt.display_name();
        let kind = if pt.is_local() { "local" } else { "cloud" };
        let key = if pt.requires_api_key() {
            ", needs API key"
        } else {
            ""
        };
        let configured = cfg
            .providers
            .iter()
            .find(|p| p.provider_type == *pt && p.is_configured());
        let status = if cfg.active().map(|a| a.provider_type) == Some(*pt) {
            " — ACTIVE"
        } else if configured.is_some() {
            " — configured"
        } else {
            ""
        };
        lines.push(format!("• {name} ({kind}{key}){status}"));
    }
    format!(
        "Available AI providers (say e.g. \"connect OpenAI\" to set one up):\n{}",
        lines.join("\n")
    )
}

/// "What provider / model am I using?" — the active provider + its model.
pub fn active_provider(cfg: &crate::llm::provider::config::ProvidersConfig) -> String {
    match cfg.active() {
        Some(p) => {
            let model = if p.active_model.is_empty() {
                "(provider default)".to_string()
            } else {
                p.active_model.clone()
            };
            format!(
                "You're using {} ({}), model {model}.",
                p.display_name,
                p.provider_type.as_str()
            )
        }
        None => format!(
            "Your active provider is \"{}\" (not found in the configured list).",
            cfg.active_provider
        ),
    }
}

/// "What changed today?" / "show recent changes" — from the durable audit ledger.
pub fn recent_changes(history: &[serde_json::Value]) -> String {
    if history.is_empty() {
        return "No recent settings changes are recorded.".to_string();
    }
    let lines: Vec<String> = history
        .iter()
        .filter_map(|entry| {
            let c = entry.get("change")?;
            let section = c.get("section").and_then(|v| v.as_str()).unwrap_or("?");
            let field = c.get("field").and_then(|v| v.as_str()).unwrap_or("?");
            if is_secret_field(section, field) {
                return Some(format!("• {section}.{field}: (secret changed)"));
            }
            let prior = c.get("prior").map(render_value).unwrap_or_default();
            let new = c.get("new").map(render_value).unwrap_or_default();
            Some(format!("• {section}.{field}: {prior} → {new}"))
        })
        .collect();
    format!("Recent settings changes:\n{}", lines.join("\n"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn list_configurable_is_schema_generated_and_grouped() {
        let all = list_configurable(None);
        assert!(all.contains("ui:"), "should group ui settings: {all}");
        assert!(all.contains("theme"));
        // Secrets never listed.
        assert!(!all.contains("cloud_api_key"));
        // Group filter.
        let voice = list_configurable(Some("voice"));
        assert!(voice.contains("voice:"));
        assert!(!voice.contains("ui:"));
    }

    #[test]
    fn explain_reports_allowed_values_and_risk() {
        let root = serde_json::to_value(crate::config::KriaConfig::default()).unwrap();
        let e = explain("ui", "theme", &root);
        assert!(e.contains("allowed: light, dark"), "{e}");
        assert!(e.contains("risk: green"), "{e}");
    }

    #[test]
    fn help_change_is_schema_generated() {
        let h = help_change("voice", "enabled");
        assert!(h.to_lowercase().contains("valid values"), "{h}");
        // YELLOW field → mentions approval.
        assert!(h.to_lowercase().contains("approve"), "{h}");
    }

    #[test]
    fn recent_changes_formats_prior_to_new() {
        let hist = vec![serde_json::json!({
            "change": {"section":"ui","field":"theme","prior":"light","new":"dark"}
        })];
        let s = recent_changes(&hist);
        assert!(s.contains("ui.theme: light → dark"), "{s}");
    }
}
