// ─────────────────────────────────────────────────────────────────────────
// KRIA design-token build (Style Dictionary → CSS custom properties)
//
// Single source of truth: tokens/base/*.json (theme-independent groups —
// space, radius, type, motion, z-index, blur, elevation) + tokens/themes/*.json
// (color values per theme). Compiles to ONE artifact:
//   src/styles/tokens.generated.css
//     :root                    → base tokens + dark color (dark is default)
//     [data-theme="light"]     → light color overrides only
//
// This is the ONLY place raw color literals are permitted. Components consume
// the generated `--color-*`, `--space-*`, etc. variables and are guarded by the
// token linter (scripts/token-lint.mjs).
// ─────────────────────────────────────────────────────────────────────────
import StyleDictionary from "style-dictionary";
import { readFileSync, writeFileSync, rmSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const uiRoot = resolve(here, "..");
const tmpDir = resolve(here, ".tmp");
const outFile = resolve(uiRoot, "src/styles/tokens.generated.css");

const BASE_GLOB = resolve(here, "base/**/*.json");
const themeFile = (t) => resolve(here, `themes/${t}.json`);

/** Build one CSS file into tmpDir for a given theme + selector. */
async function buildThemeFile({ source, destination, selector, filter }) {
  const sd = new StyleDictionary({
    source,
    platforms: {
      css: {
        transformGroup: "css",
        buildPath: tmpDir + "/",
        files: [
          {
            destination,
            format: "css/variables",
            filter,
            options: { selector, outputReferences: false },
          },
        ],
      },
    },
    log: { verbosity: "silent" },
  });
  await sd.buildAllPlatforms();
}

// Namespaces whose values differ between themes (dark/light parity). Tokens in
// these groups are emitted into the [data-theme="light"] overrides file; every
// other (theme-independent) group lives only in :root. `color` is the original
// palette; the presence-redesign adds shared-light (`core`), environmental room
// gradient (`room`), the Reading Mode near-solid backing + hard-dim (`reading`),
// glass/material (`glass`), and presence-state hues (`presence`) — all of which
// resolve to theme-specific color values.
const THEME_NAMESPACES = new Set(["color", "core", "room", "reading", "glass", "presence"]);

/** Theme-scoped tokens (used for the light overrides file). */
const themeScoped = (token) => THEME_NAMESPACES.has(token.path[0]);

async function main() {
  mkdirSync(tmpDir, { recursive: true });

  // :root — every base token + the dark color palette (dark is the default theme)
  await buildThemeFile({
    source: [BASE_GLOB, themeFile("dark")],
    destination: "dark.css",
    selector: ":root",
  });

  // [data-theme="light"] — color overrides only (base tokens are theme-independent)
  await buildThemeFile({
    source: [BASE_GLOB, themeFile("light")],
    destination: "light.css",
    selector: '[data-theme="light"]',
    filter: themeScoped,
  });

  const header =
    "/**\n" +
    " * AUTO-GENERATED by tokens/build.mjs — DO NOT EDIT BY HAND.\n" +
    " * Edit tokens/base/*.json or tokens/themes/*.json, then run `npm run tokens:build`.\n" +
    " * Single design-token source (Req 14.1); dark + light parity (Req 14.1).\n" +
    " */\n\n";

  const dark = readFileSync(resolve(tmpDir, "dark.css"), "utf8");
  const light = readFileSync(resolve(tmpDir, "light.css"), "utf8");

  writeFileSync(outFile, header + dark + "\n" + light);
  rmSync(tmpDir, { recursive: true, force: true });

  console.log(`✓ tokens → ${outFile.replace(uiRoot + "/", "")}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
