//! Dynamic Tool Generation — self-extending capabilities.
//!
//! # Architecture
//!
//! ```text
//! ┌──────────────────┐
//! │  API Documentation│  ← OpenAPI spec, CLI --help, README
//! │  or CLI Help Text │
//! └────────┬─────────┘
//!          │
//!          ▼
//! ┌──────────────────┐
//! │  Tool Generator   │  ← LLM generates ToolDef from docs
//! │  (LLM-backed)     │
//! └────────┬─────────┘
//!          │
//!          ▼
//! ┌──────────────────┐
//! │  SchemaValidator  │  ← deterministic validation
//! │  + Dry-Run Gate   │
//! └────────┬─────────┘
//!          │
//!          ▼
//! ┌──────────────────┐
//! │  QuarantineRegistry│  ← NOT auto-promoted
//! └──────────────────┘
//! ```
//!
//! # Safety: Idempotent-Only Dry Runs
//!
//! The `SchemaValidator` can dry-run generated tools to verify they execute
//! without errors. However, dry-runs are ONLY allowed for idempotent operations:
//!
//! - ✅ GET, HEAD, OPTIONS (HTTP read-only)
//! - ✅ CLI commands with `--help`, `--version`, `--dry-run`
//! - ✅ `list`, `status`, `show`, `get`, `describe`, `info` commands
//! - ❌ POST, PUT, DELETE, PATCH (HTTP mutative)
//! - ❌ `install`, `remove`, `delete`, `create`, `modify`, `set` commands
//! - ❌ Any command without a recognized safe flag
//!
//! Mutative operations are sent directly to the QuarantineRegistry without
//! dry-run — they must be validated through HITL approval instead.

use std::collections::HashSet;
use std::sync::Arc;

use crate::safety::policy_gate::PolicyGate;
use crate::safety::RiskLevel;
use crate::tools::quarantine::{QuarantineRegistry, ToolSource};

// ─── Generated Tool ─────────────────────────────────────────────────────────

/// A tool definition generated by the LLM from API/CLI documentation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GeneratedToolDef {
    /// Tool name (snake_case).
    pub name: String,
    /// Human-readable description.
    pub description: String,
    /// Category (e.g., "http_api", "cli_tool", "system").
    pub category: String,
    /// JSON Schema for the tool's parameters.
    pub parameters_schema: serde_json::Value,
    /// The command or API call template.
    pub invocation: ToolInvocation,
    /// Whether this tool is idempotent (safe to dry-run).
    pub idempotent: bool,
    /// The source documentation.
    pub source_docs: String,
}

/// How the tool is invoked.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub enum ToolInvocation {
    /// CLI command: binary + arg template.
    /// Variables are `{param_name}` placeholders.
    Cli {
        binary: String,
        args_template: Vec<String>,
    },
    /// HTTP API call.
    Http {
        method: HttpMethod,
        url_template: String,
        headers: std::collections::HashMap<String, String>,
        body_template: Option<String>,
    },
}

/// HTTP methods.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum HttpMethod {
    Get,
    Head,
    Post,
    Put,
    Delete,
    Patch,
    Options,
}

impl HttpMethod {
    /// Returns `true` if this method is read-only (safe to dry-run).
    pub fn is_read_only(&self) -> bool {
        matches!(self, Self::Get | Self::Head | Self::Options)
    }
}

// ─── Validation Result ──────────────────────────────────────────────────────

/// Result of schema validation.
#[derive(Debug, Clone)]
pub struct ValidationResult {
    /// Whether the tool passed validation.
    pub valid: bool,
    /// The validated tool definition (if valid).
    pub tool: Option<GeneratedToolDef>,
    /// Validation errors (if invalid).
    pub errors: Vec<ValidationError>,
    /// Whether a dry-run was attempted and its result.
    pub dry_run_result: Option<DryRunResult>,
}

/// A validation error.
#[derive(Debug, Clone)]
pub struct ValidationError {
    pub field: String,
    pub message: String,
    pub severity: ValidationSeverity,
}

/// Severity of a validation error.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ValidationSeverity {
    /// Tool cannot be used.
    Error,
    /// Tool can be used but with caution.
    Warning,
}

/// Result of a dry-run attempt.
#[derive(Debug, Clone)]
pub enum DryRunResult {
    /// Dry-run succeeded.
    Success { output: String },
    /// Dry-run was skipped (non-idempotent).
    Skipped { reason: String },
    /// Dry-run failed.
    Failed { error: String },
}

// ─── Schema Validator ───────────────────────────────────────────────────────

/// Validates and dry-runs generated tool definitions.
///
/// # Idempotent-Only Dry Runs
///
/// The validator explicitly rejects dry-runs for non-idempotent operations.
/// This prevents accidental state mutation during validation.
pub struct SchemaValidator {
    /// Policy gate for evaluating CLI commands.
    policy_gate: Arc<dyn PolicyGate>,
    /// CLI commands known to be safe for dry-run (accept --help or --version).
    safe_dry_run_binaries: HashSet<String>,
    /// CLI flags that indicate a dry-run is safe.
    safe_dry_run_flags: HashSet<String>,
    /// CLI prefixes that indicate a read-only operation.
    safe_cli_prefixes: HashSet<String>,
}

impl SchemaValidator {
    pub fn new(policy_gate: Arc<dyn PolicyGate>) -> Self {
        let mut safe_binaries = HashSet::new();
        // Common CLI tools that accept --help without side effects.
        for binary in &[
            "ls",
            "cat",
            "head",
            "tail",
            "grep",
            "find",
            "wc",
            "sort",
            "awk",
            "sed",
            "cut",
            "tr",
            "diff",
            "file",
            "stat",
            "du",
            "df",
            "free",
            "top",
            "ps",
            "uptime",
            "uname",
            "hostname",
            "ip",
            "ss",
            "ping",
            "traceroute",
            "dig",
            "curl",
            "wget",
            "git",
            "docker",
            "podman",
            "systemctl",
            "journalctl",
            "lscpu",
            "lspci",
            "lsusb",
            "lsblk",
            "jq",
            "tree",
            "python3",
            "node",
            "npm",
            "pip",
            "cargo",
            "rustc",
        ] {
            safe_binaries.insert(binary.to_string());
        }

        let mut safe_flags = HashSet::new();
        for flag in &[
            "--help",
            "-h",
            "--version",
            "-V",
            "-v",
            "--dry-run",
            "--dry-run",
            "--list",
            "--status",
            "--info",
            "--show",
            "--describe",
            "--get",
            "--check",
            "--verify",
            "--test",
            "--print-config",
            "--dump",
            "--query",
            "--search",
            "--whoami",
            "--me",
            "status",
            "list",
            "show",
            "get",
            "describe",
            "info",
            "help",
            "version",
        ] {
            safe_flags.insert(flag.to_string());
        }

        let mut safe_prefixes = HashSet::new();
        for prefix in &[
            "list", "get", "show", "describe", "info", "status", "check", "verify", "search",
            "find", "query", "read", "fetch", "browse", "inspect", "examine", "audit",
        ] {
            safe_prefixes.insert(prefix.to_string());
        }

        Self {
            policy_gate,
            safe_dry_run_binaries: safe_binaries,
            safe_dry_run_flags: safe_flags,
            safe_cli_prefixes: safe_prefixes,
        }
    }

    /// Validate a generated tool definition.
    ///
    /// This performs:
    /// 1. Schema validation (required fields, valid types)
    /// 2. Idempotency check (can we dry-run safely?)
    /// 3. Dry-run (if idempotent)
    /// 4. Policy gate evaluation
    pub async fn validate(&self, tool: GeneratedToolDef) -> ValidationResult {
        let mut errors = Vec::new();

        // 1. Schema validation.
        self.validate_schema(&tool, &mut errors);

        // 2. Check idempotency.
        let can_dry_run = self.can_dry_run(&tool);

        // 3. Dry-run (if allowed).
        let dry_run_result = if can_dry_run {
            match self.dry_run(&tool).await {
                Ok(output) => Some(DryRunResult::Success { output }),
                Err(e) => {
                    errors.push(ValidationError {
                        field: "invocation".to_string(),
                        message: format!("Dry-run failed: {}", e),
                        severity: ValidationSeverity::Warning, // Warning, not error — tool may still work with real params
                    });
                    Some(DryRunResult::Failed { error: e })
                }
            }
        } else {
            let reason = self.explain_why_not_dry_run(&tool);
            Some(DryRunResult::Skipped { reason })
        };

        // 4. Policy gate evaluation (for CLI tools).
        if let ToolInvocation::Cli { binary, .. } = &tool.invocation {
            let risk = self.policy_gate.classify_risk(binary, &[]);
            if risk == RiskLevel::Black {
                errors.push(ValidationError {
                    field: "invocation.binary".to_string(),
                    message: format!("Binary '{}' is permanently blocked", binary),
                    severity: ValidationSeverity::Error,
                });
            }
        }

        let valid = errors
            .iter()
            .all(|e| e.severity != ValidationSeverity::Error);

        ValidationResult {
            valid,
            tool: if valid { Some(tool) } else { None },
            errors,
            dry_run_result,
        }
    }

    /// Validate the schema of a generated tool.
    fn validate_schema(&self, tool: &GeneratedToolDef, errors: &mut Vec<ValidationError>) {
        // Name must be non-empty snake_case.
        if tool.name.is_empty() {
            errors.push(ValidationError {
                field: "name".to_string(),
                message: "Tool name is empty".to_string(),
                severity: ValidationSeverity::Error,
            });
        } else if !tool.name.chars().all(|c| c.is_alphanumeric() || c == '_') {
            errors.push(ValidationError {
                field: "name".to_string(),
                message: format!(
                    "Tool name '{}' contains invalid characters (must be snake_case)",
                    tool.name
                ),
                severity: ValidationSeverity::Error,
            });
        }

        // Description must be non-empty.
        if tool.description.is_empty() {
            errors.push(ValidationError {
                field: "description".to_string(),
                message: "Tool description is empty".to_string(),
                severity: ValidationSeverity::Error,
            });
        }

        // Parameters schema must be a valid JSON Schema object.
        if !tool.parameters_schema.is_object() {
            errors.push(ValidationError {
                field: "parameters_schema".to_string(),
                message: "Parameters schema must be a JSON object".to_string(),
                severity: ValidationSeverity::Error,
            });
        }

        // Invocation must have required fields.
        match &tool.invocation {
            ToolInvocation::Cli { binary, .. } => {
                if binary.is_empty() {
                    errors.push(ValidationError {
                        field: "invocation.binary".to_string(),
                        message: "CLI binary is empty".to_string(),
                        severity: ValidationSeverity::Error,
                    });
                }
                // Check for shell metacharacters in binary name.
                if binary.contains(|c: char| ";|&`$(){}<>\\".contains(c)) {
                    errors.push(ValidationError {
                        field: "invocation.binary".to_string(),
                        message: format!("Binary '{}' contains shell metacharacters", binary),
                        severity: ValidationSeverity::Error,
                    });
                }
            }
            ToolInvocation::Http {
                method,
                url_template,
                ..
            } => {
                if url_template.is_empty() {
                    errors.push(ValidationError {
                        field: "invocation.url_template".to_string(),
                        message: "URL template is empty".to_string(),
                        severity: ValidationSeverity::Error,
                    });
                }
                // Warn about mutative methods.
                if !method.is_read_only() {
                    errors.push(ValidationError {
                        field: "invocation.method".to_string(),
                        message: format!(
                            "HTTP {:?} is mutative — dry-run will be skipped, HITL approval required",
                            method
                        ),
                        severity: ValidationSeverity::Warning,
                    });
                }
            }
        }
    }

    /// Check if a tool can be safely dry-run.
    ///
    /// Returns `true` ONLY if the operation is idempotent.
    fn can_dry_run(&self, tool: &GeneratedToolDef) -> bool {
        // Explicit idempotent flag.
        if !tool.idempotent {
            return false;
        }

        match &tool.invocation {
            ToolInvocation::Cli {
                binary,
                args_template,
            } => self.can_dry_run_cli(binary, args_template),
            ToolInvocation::Http { method, .. } => {
                // Only GET, HEAD, OPTIONS are safe.
                method.is_read_only()
            }
        }
    }

    /// Check if a CLI command can be safely dry-run.
    fn can_dry_run_cli(&self, binary: &str, args_template: &[String]) -> bool {
        // Binary must be in the safe list.
        if !self.safe_dry_run_binaries.contains(binary) {
            return false;
        }

        // If there are no args, we can try --help.
        if args_template.is_empty() {
            return true;
        }

        // Check if the first arg is a safe flag or safe subcommand.
        if let Some(first_arg) = args_template.first() {
            // Strip leading dashes for subcommand check.
            let bare = first_arg.trim_start_matches('-');

            // Safe if it's a known safe flag.
            if self.safe_dry_run_flags.contains(first_arg) {
                return true;
            }

            // Safe if it's a known safe subcommand prefix.
            if self.safe_cli_prefixes.contains(bare) {
                return true;
            }
        }

        // Check if ANY arg contains a safe flag.
        for arg in args_template {
            if self.safe_dry_run_flags.contains(arg) {
                return true;
            }
        }

        // Unknown args — not safe to dry-run.
        false
    }

    /// Explain why a tool cannot be dry-run.
    fn explain_why_not_dry_run(&self, tool: &GeneratedToolDef) -> String {
        match &tool.invocation {
            ToolInvocation::Http { method, .. } => {
                if !method.is_read_only() {
                    return format!("HTTP {:?} is mutative — cannot dry-run safely", method);
                }
                "HTTP method is read-only but tool is not marked idempotent".to_string()
            }
            ToolInvocation::Cli {
                binary,
                args_template,
            } => {
                if !tool.idempotent {
                    return "Tool is explicitly marked as non-idempotent".to_string();
                }
                if !self.safe_dry_run_binaries.contains(binary) {
                    return format!("Binary '{}' is not in the safe dry-run list", binary);
                }
                if let Some(first_arg) = args_template.first() {
                    let bare = first_arg.trim_start_matches('-');
                    if !self.safe_dry_run_flags.contains(first_arg)
                        && !self.safe_cli_prefixes.contains(bare)
                    {
                        return format!(
                            "First argument '{}' is not a recognized safe flag or subcommand",
                            first_arg
                        );
                    }
                }
                "Unknown reason".to_string()
            }
        }
    }

    /// Execute a dry-run of the tool.
    ///
    /// For CLI tools: runs the command with `--help` or `--dry-run` flag.
    /// For HTTP tools: sends a GET/HEAD request to the URL.
    async fn dry_run(&self, tool: &GeneratedToolDef) -> Result<String, String> {
        match &tool.invocation {
            ToolInvocation::Cli { binary, .. } => {
                // Run with --help flag.
                let output = tokio::process::Command::new(binary)
                    .arg("--help")
                    .output()
                    .await
                    .map_err(|e| format!("Failed to execute '{} --help': {}", binary, e))?;

                let stdout = String::from_utf8_lossy(&output.stdout);
                let stderr = String::from_utf8_lossy(&output.stderr);

                if output.status.success() || !stdout.is_empty() {
                    Ok(format!("{}\n{}", stdout, stderr).trim().to_string())
                } else {
                    // Try --version as fallback.
                    let version_output = tokio::process::Command::new(binary)
                        .arg("--version")
                        .output()
                        .await
                        .map_err(|e| format!("Failed to execute '{} --version': {}", binary, e))?;

                    if version_output.status.success() {
                        Ok(String::from_utf8_lossy(&version_output.stdout)
                            .trim()
                            .to_string())
                    } else {
                        Err(format!("Both --help and --version failed for '{}'", binary))
                    }
                }
            }
            ToolInvocation::Http {
                url_template,
                headers,
                ..
            } => {
                // Replace template variables with test values.
                let test_url = url_template
                    .replace("{id}", "0")
                    .replace("{name}", "test")
                    .replace("{key}", "test");

                let client = reqwest::Client::new();
                let mut request = client.head(&test_url);

                for (key, value) in headers {
                    request = request.header(key, value);
                }

                let response = request
                    .timeout(std::time::Duration::from_secs(10))
                    .send()
                    .await
                    .map_err(|e| format!("HTTP dry-run failed: {}", e))?;

                Ok(format!("HTTP {} → {}", test_url, response.status()))
            }
        }
    }
}

// ─── Dynamic Tool Generator ─────────────────────────────────────────────────

/// Generates tool definitions from API documentation or CLI help text.
pub struct DynamicToolGenerator {
    validator: SchemaValidator,
    quarantine: Arc<QuarantineRegistry>,
}

impl DynamicToolGenerator {
    pub fn new(validator: SchemaValidator, quarantine: Arc<QuarantineRegistry>) -> Self {
        Self {
            validator,
            quarantine,
        }
    }

    /// Generate and validate a tool from documentation.
    ///
    /// The LLM generates a `GeneratedToolDef` from the provided docs.
    /// The `SchemaValidator` validates it and optionally dry-runs it.
    /// If valid, the tool is sent to the `QuarantineRegistry`.
    pub async fn register_from_docs(
        &self,
        _docs: &str,
        generated: GeneratedToolDef,
    ) -> Result<RegistrationResult, String> {
        let tool_name = generated.name.clone();
        let risk_level = self.estimate_risk(&generated);

        // Validate the generated tool.
        let validation = self.validator.validate(generated).await;

        if !validation.valid {
            let errors: Vec<String> = validation
                .errors
                .iter()
                .map(|e| e.message.clone())
                .collect();
            return Ok(RegistrationResult::ValidationFailed { tool_name, errors });
        }

        let _tool = validation.tool.unwrap();

        // Register in quarantine.
        self.quarantine
            .quarantine(&tool_name, risk_level, ToolSource::DynamicDiscovery)
            .map_err(|e| format!("Failed to quarantine tool: {}", e))?;

        Ok(RegistrationResult::Quarantined {
            tool_name,
            risk_level,
            dry_run_result: validation.dry_run_result,
        })
    }

    /// Estimate the risk level of a generated tool.
    fn estimate_risk(&self, tool: &GeneratedToolDef) -> RiskLevel {
        match &tool.invocation {
            ToolInvocation::Cli {
                binary,
                args_template,
            } => {
                let risk = self.validator.policy_gate.classify_risk(binary, &[]);
                if risk != RiskLevel::Green {
                    return risk;
                }

                // Check if the first arg indicates a mutative operation.
                if let Some(first_arg) = args_template.first() {
                    let bare = first_arg.trim_start_matches('-');
                    let destructive_prefixes = [
                        "delete",
                        "remove",
                        "rm",
                        "kill",
                        "stop",
                        "destroy",
                        "drop",
                        "truncate",
                        "purge",
                        "wipe",
                        "erase",
                        "nuke",
                        "install",
                        "uninstall",
                        "apt",
                        "apt-get",
                        "pip",
                        "push",
                        "force",
                        "reset",
                        "revert",
                        "undo",
                    ];
                    if destructive_prefixes.contains(&bare) {
                        return RiskLevel::Red;
                    }

                    let write_prefixes = [
                        "create", "add", "set", "update", "modify", "write", "edit", "patch",
                        "move", "rename", "copy", "cp", "start", "restart", "enable", "disable",
                    ];
                    if write_prefixes.contains(&bare) {
                        return RiskLevel::Yellow;
                    }
                }

                RiskLevel::Green
            }
            ToolInvocation::Http { method, .. } => match method {
                HttpMethod::Get | HttpMethod::Head | HttpMethod::Options => RiskLevel::Green,
                HttpMethod::Post | HttpMethod::Put | HttpMethod::Patch => RiskLevel::Yellow,
                HttpMethod::Delete => RiskLevel::Red,
            },
        }
    }
}

/// Result of a tool registration attempt.
#[derive(Debug, Clone)]
pub enum RegistrationResult {
    /// Tool passed validation and was sent to quarantine.
    Quarantined {
        tool_name: String,
        risk_level: RiskLevel,
        dry_run_result: Option<DryRunResult>,
    },
    /// Tool failed validation.
    ValidationFailed {
        tool_name: String,
        errors: Vec<String>,
    },
}

// ─── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::safety::policy_gate::CapabilityPolicyGate;

    fn make_validator() -> SchemaValidator {
        let policy_gate = Arc::new(CapabilityPolicyGate::new());
        SchemaValidator::new(policy_gate)
    }

    fn make_cli_tool(
        name: &str,
        binary: &str,
        args: Vec<&str>,
        idempotent: bool,
    ) -> GeneratedToolDef {
        GeneratedToolDef {
            name: name.to_string(),
            description: format!("Test tool: {}", name),
            category: "cli_tool".to_string(),
            parameters_schema: serde_json::json!({"type": "object", "properties": {}}),
            invocation: ToolInvocation::Cli {
                binary: binary.to_string(),
                args_template: args.into_iter().map(String::from).collect(),
            },
            idempotent,
            source_docs: "test".to_string(),
        }
    }

    fn make_http_tool(name: &str, method: HttpMethod, url: &str) -> GeneratedToolDef {
        GeneratedToolDef {
            name: name.to_string(),
            description: format!("Test tool: {}", name),
            category: "http_api".to_string(),
            parameters_schema: serde_json::json!({"type": "object", "properties": {}}),
            invocation: ToolInvocation::Http {
                method,
                url_template: url.to_string(),
                headers: std::collections::HashMap::new(),
                body_template: None,
            },
            idempotent: method.is_read_only(),
            source_docs: "test".to_string(),
        }
    }

    // ── Schema Validation Tests ─────────────────────────────────────────────

    #[tokio::test]
    async fn test_valid_cli_tool() {
        let validator = make_validator();
        let tool = make_cli_tool("list_files", "ls", vec!["-la"], true);
        let result = validator.validate(tool).await;
        assert!(
            result.valid,
            "Expected valid, got errors: {:?}",
            result.errors
        );
    }

    #[tokio::test]
    async fn test_empty_name_rejected() {
        let validator = make_validator();
        let tool = make_cli_tool("", "ls", vec![], true);
        let result = validator.validate(tool).await;
        assert!(!result.valid);
        assert!(result.errors.iter().any(|e| e.field == "name"));
    }

    #[tokio::test]
    async fn test_invalid_name_chars_rejected() {
        let validator = make_validator();
        let tool = make_cli_tool("list files", "ls", vec![], true);
        let result = validator.validate(tool).await;
        assert!(!result.valid);
    }

    #[tokio::test]
    async fn test_shell_metacharacters_in_binary_rejected() {
        let validator = make_validator();
        let tool = make_cli_tool("bad_tool", "ls; rm -rf /", vec![], true);
        let result = validator.validate(tool).await;
        assert!(!result.valid);
        assert!(result.errors.iter().any(|e| e.field == "invocation.binary"));
    }

    #[tokio::test]
    async fn test_empty_description_rejected() {
        let validator = make_validator();
        let mut tool = make_cli_tool("test", "ls", vec![], true);
        tool.description = String::new();
        let result = validator.validate(tool).await;
        assert!(!result.valid);
    }

    #[tokio::test]
    async fn test_non_json_schema_rejected() {
        let validator = make_validator();
        let mut tool = make_cli_tool("test", "ls", vec![], true);
        tool.parameters_schema = serde_json::json!("not an object");
        let result = validator.validate(tool).await;
        assert!(!result.valid);
    }

    // ── Idempotent-Only Dry Run Tests ──────────────────────────────────────

    #[tokio::test]
    async fn test_dry_run_blocked_for_non_idempotent_tool() {
        let validator = make_validator();
        // Tool is explicitly non-idempotent.
        let tool = make_cli_tool("install_pkg", "apt", vec!["install", "nginx"], false);
        assert!(!validator.can_dry_run(&tool));
    }

    #[tokio::test]
    async fn test_dry_run_allowed_for_idempotent_help_flag() {
        let validator = make_validator();
        // ls --help is idempotent and safe.
        let tool = make_cli_tool("list_files", "ls", vec!["--help"], true);
        assert!(validator.can_dry_run(&tool));
    }

    #[tokio::test]
    async fn test_dry_run_allowed_for_status_subcommand() {
        let validator = make_validator();
        // systemctl status is read-only.
        let tool = make_cli_tool("check_service", "systemctl", vec!["status", "nginx"], true);
        assert!(validator.can_dry_run(&tool));
    }

    #[tokio::test]
    async fn test_dry_run_blocked_for_install_subcommand() {
        let validator = make_validator();
        // apt install is mutative.
        let tool = make_cli_tool("install_pkg", "apt", vec!["install", "nginx"], true);
        assert!(!validator.can_dry_run(&tool));
    }

    #[tokio::test]
    async fn test_dry_run_blocked_for_unsafe_binary() {
        let validator = make_validator();
        // Binary not in safe list.
        let tool = make_cli_tool("custom_tool", "some_unknown_binary", vec!["--help"], true);
        assert!(!validator.can_dry_run(&tool));
    }

    #[tokio::test]
    async fn test_dry_run_blocked_for_http_post() {
        let validator = make_validator();
        let tool = make_http_tool(
            "create_item",
            HttpMethod::Post,
            "https://api.example.com/items",
        );
        assert!(!validator.can_dry_run(&tool));
    }

    #[tokio::test]
    async fn test_dry_run_blocked_for_http_delete() {
        let validator = make_validator();
        let tool = make_http_tool(
            "delete_item",
            HttpMethod::Delete,
            "https://api.example.com/items/{id}",
        );
        assert!(!validator.can_dry_run(&tool));
    }

    #[tokio::test]
    async fn test_dry_run_allowed_for_http_get() {
        let validator = make_validator();
        let tool = make_http_tool(
            "get_item",
            HttpMethod::Get,
            "https://api.example.com/items/{id}",
        );
        assert!(validator.can_dry_run(&tool));
    }

    #[tokio::test]
    async fn test_dry_run_blocked_for_http_put() {
        let validator = make_validator();
        let tool = make_http_tool(
            "update_item",
            HttpMethod::Put,
            "https://api.example.com/items/{id}",
        );
        assert!(!validator.can_dry_run(&tool));
    }

    #[tokio::test]
    async fn test_dry_run_skipped_result_for_non_idempotent() {
        let validator = make_validator();
        let tool = make_cli_tool("install_pkg", "apt", vec!["install", "nginx"], false);
        let result = validator.validate(tool).await;
        // Should be valid (schema is OK) but dry-run should be skipped.
        assert!(result.valid);
        match result.dry_run_result {
            Some(DryRunResult::Skipped { .. }) => {} // Expected
            other => panic!("Expected Skipped, got {:?}", other),
        }
    }

    #[tokio::test]
    async fn test_dry_run_explanation_for_non_idempotent() {
        let validator = make_validator();
        let tool = make_cli_tool(
            "deploy",
            "kubectl",
            vec!["apply", "-f", "deploy.yaml"],
            false,
        );
        let reason = validator.explain_why_not_dry_run(&tool);
        assert!(reason.contains("non-idempotent"));
    }

    #[tokio::test]
    async fn test_dry_run_explanation_for_mutative_http() {
        let validator = make_validator();
        let tool = make_http_tool("create", HttpMethod::Post, "https://api.example.com/items");
        let reason = validator.explain_why_not_dry_run(&tool);
        assert!(reason.contains("mutative"));
    }

    // ── Risk Estimation Tests ──────────────────────────────────────────────

    #[test]
    fn test_http_get_is_green() {
        assert!(HttpMethod::Get.is_read_only());
        assert!(HttpMethod::Head.is_read_only());
        assert!(HttpMethod::Options.is_read_only());
    }

    #[test]
    fn test_http_post_is_not_read_only() {
        assert!(!HttpMethod::Post.is_read_only());
        assert!(!HttpMethod::Put.is_read_only());
        assert!(!HttpMethod::Delete.is_read_only());
        assert!(!HttpMethod::Patch.is_read_only());
    }

    // ── Blocked Binary Tests ───────────────────────────────────────────────

    #[tokio::test]
    async fn test_blocked_binary_rejected() {
        let validator = make_validator();
        // "dd" is permanently blocked.
        let tool = make_cli_tool("disk_copy", "dd", vec!["if=/dev/zero", "of=/dev/sda"], true);
        let result = validator.validate(tool).await;
        assert!(!result.valid);
        assert!(result
            .errors
            .iter()
            .any(|e| e.message.contains("permanently blocked")));
    }
}
