/**
 * build-icons.mjs — Build the Lucide SVG sprite (Req 14.6, design.md §1.15).
 *
 * Reads the icon allow-list in `scripts/icon-manifest.json`, pulls each icon's
 * SVG from the `lucide-static` package, and emits a single sprite of <symbol>s
 * to `ui/public/icons/lucide-sprite.svg`. Components reference symbols via the
 * <Icon> component (`src/components/Icon.tsx`) → zero per-icon runtime cost and
 * one consistent stroke weight. Emoji is reserved for user content only.
 *
 * To add an icon: add its kebab-case name (a Lucide icon id) to the manifest
 * and re-run `npm run icons:build`.
 */
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const uiRoot = join(__dirname, "..");
const manifestPath = join(__dirname, "icon-manifest.json");
const iconsDir = join(uiRoot, "node_modules", "lucide-static", "icons");
const outDir = join(uiRoot, "public", "icons");
const outFile = join(outDir, "lucide-sprite.svg");

// Pull the inner geometry out of a lucide SVG file (drops the outer <svg> and
// the license comment). Every lucide icon shares viewBox="0 0 24 24" and the
// stroke attributes, which we set once on the consuming <svg> via CSS.
function extractInner(svg) {
  const open = svg.indexOf(">", svg.indexOf("<svg"));
  const close = svg.lastIndexOf("</svg>");
  if (open === -1 || close === -1) return "";
  return svg.slice(open + 1, close).trim();
}

function main() {
  const names = JSON.parse(readFileSync(manifestPath, "utf8"));
  if (!Array.isArray(names) || names.length === 0) {
    console.error("[build-icons] icon-manifest.json must be a non-empty array of lucide icon names.");
    process.exitCode = 1;
    return;
  }

  const symbols = [];
  const missing = [];
  for (const name of [...new Set(names)].sort()) {
    const src = join(iconsDir, `${name}.svg`);
    if (!existsSync(src)) {
      missing.push(name);
      continue;
    }
    const inner = extractInner(readFileSync(src, "utf8"));
    symbols.push(`  <symbol id="${name}" viewBox="0 0 24 24">${inner}</symbol>`);
  }

  if (missing.length) {
    console.warn(`[build-icons] WARNING: ${missing.length} icon(s) not found in lucide-static:`);
    for (const m of missing) console.warn(`  - ${m}`);
  }

  mkdirSync(outDir, { recursive: true });
  const sprite = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!-- AUTO-GENERATED by scripts/build-icons.mjs — DO NOT EDIT. Edit scripts/icon-manifest.json + run \`npm run icons:build\`. -->`,
    `<svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:none">`,
    ...symbols,
    `</svg>`,
    "",
  ].join("\n");
  writeFileSync(outFile, sprite);
  console.log(`[build-icons] Wrote ${symbols.length} icon symbol(s) to public/icons/lucide-sprite.svg`);
}

main();
