#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
cd "$ROOT_DIR"

export KRIA_TEST_ALLOW_DESTRUCTIVE="${KRIA_TEST_ALLOW_DESTRUCTIVE:-1}"
export KRIA_TEST_SNAPSHOT="${KRIA_TEST_SNAPSHOT:-1}"
export KRIA_REAL_LLM="${KRIA_REAL_LLM:-1}"
export KRIA_BEHAVIOR_GOLDEN="${KRIA_BEHAVIOR_GOLDEN:-1}"
export KRIA_QUALITY_STRICT_API="${KRIA_QUALITY_STRICT_API:-1}"
export KRIA_COGNITIVE_MIN_MAIN="${KRIA_COGNITIVE_MIN_MAIN:-75}"
export KRIA_COGNITIVE_MIN_VM="${KRIA_COGNITIVE_MIN_VM:-97}"
export KRIA_COGNITIVE_MIN_AGGREGATE="${KRIA_COGNITIVE_MIN_AGGREGATE:-82}"
export KRIA_REQUIRE_REPORTS="${KRIA_REQUIRE_REPORTS:-1}"
export KRIA_TREND_COGNITIVE_FLOOR="${KRIA_TREND_COGNITIVE_FLOOR:-60}"

echo "==> Running production release gate profile (RELEASE)"
cargo kria-test --mode RELEASE "$@"

