/**
 * Machine Store — fleet, devices, remote desktop state.
 *
 * Requirements: 8.1 (fleet matrix), 8.2 (remote desktop), 8.4 (mobile)
 */
import { createSignal } from "solid-js";
import { eventBus } from "./eventBus";
import { bridgeInvoke } from "../bridge/invoke";
import type { ServiceResult } from "../bridge/types";

// ─── Types ─────────────────────────────────────────────────────────────────────

export type DeviceStatus = "online" | "offline" | "busy" | "error" | "enrolling";

/**
 * Enrollment request — mirrors the EXISTING `register_new_target` command
 * contract (camelCase fields, deserialized by the runtime). Task 9.1 does not
 * change this contract.
 */
export interface EnrollTargetRequest {
  displayName: string;
  host: string;
  port: number;
  username: string;
  sshPrivateKeyPath?: string;
  expectedHostkeySha256?: string;
}

export interface Device {
  id: string;
  name: string;
  type: "desktop" | "server" | "mobile" | "vm";
  status: DeviceStatus;
  os: string;
  lastSeen: number;
  ip?: string;
}

export interface RemoteSession {
  deviceId: string;
  active: boolean;
  resolution?: { width: number; height: number };
}

export type RemoteDesktopState =
  | "idle"
  | "pending_approval"
  | "active"
  | "stopped"
  | "expired";

/** Exact snapshot returned by the existing `remote_desktop_status` command. */
export interface RemoteDesktopStatus {
  state: RemoteDesktopState;
  session_id: string | null;
  started_at: number | null;
  last_activity: number | null;
  idle_timeout_secs: number;
  running: boolean;
  backend: string;
}

/** Exact public mobile-device record. Secrets never cross this boundary. */
export interface MobileDeviceInfo {
  id: string;
  name: string;
  created_at: number;
  last_seen: number;
  revoked: boolean;
}

/** Mobile gateway lifecycle snapshot from KRIA's desktop runtime. */
export interface MobileGatewayStatus {
  mobile_enabled: boolean;
  remote_desktop_enabled: boolean;
  running: boolean;
  bound_addr: string | null;
  device_count: number;
  remote_desktop: RemoteDesktopStatus;
}

/** Short-lived, single-use pairing challenge generated by KRIA. */
export interface MobilePairingChallenge {
  code: string;
  qr_payload: string;
  expires_at: number;
  server_url: string;
  mobile_url: string;
}

/** Preserve signal identity when poll responses contain no state change. */
export function sameRemoteDesktopStatus(
  left: RemoteDesktopStatus | null,
  right: RemoteDesktopStatus | null,
): boolean {
  if (left === right) return true;
  if (!left || !right) return false;
  return left.state === right.state
    && left.session_id === right.session_id
    && left.started_at === right.started_at
    && left.last_activity === right.last_activity
    && left.idle_timeout_secs === right.idle_timeout_secs
    && left.running === right.running
    && left.backend === right.backend;
}

export function sameMobileGatewayStatus(
  left: MobileGatewayStatus | null,
  right: MobileGatewayStatus | null,
): boolean {
  if (left === right) return true;
  if (!left || !right) return false;
  return left.mobile_enabled === right.mobile_enabled
    && left.remote_desktop_enabled === right.remote_desktop_enabled
    && left.running === right.running
    && left.bound_addr === right.bound_addr
    && left.device_count === right.device_count
    && sameRemoteDesktopStatus(left.remote_desktop, right.remote_desktop);
}

export function sameMobileDevices(
  left: readonly MobileDeviceInfo[],
  right: readonly MobileDeviceInfo[],
): boolean {
  return left === right || (left.length === right.length && left.every((device, index) => {
    const candidate = right[index];
    return device.id === candidate.id
      && device.name === candidate.name
      && device.created_at === candidate.created_at
      && device.last_seen === candidate.last_seen
      && device.revoked === candidate.revoked;
  }));
}

// ─── Signals ───────────────────────────────────────────────────────────────────

const [devices, setDevices] = createSignal<Device[]>([]);
const [activeRemoteSession, setActiveRemoteSession] = createSignal<RemoteSession | null>(null);
const [remoteDesktopStatus, setRemoteDesktopStatus] = createSignal<RemoteDesktopStatus | null>(null);
const [remoteDesktopError, setRemoteDesktopError] = createSignal<string | null>(null);
const [remoteDesktopBusy, setRemoteDesktopBusy] = createSignal(false);
const [enrollmentPending, setEnrollmentPending] = createSignal(false);
const [mobileGatewayStatus, setMobileGatewayStatus] = createSignal<MobileGatewayStatus | null>(null);
const [mobileDevices, setMobileDevices] = createSignal<MobileDeviceInfo[]>([]);
const [mobilePairing, setMobilePairing] = createSignal<MobilePairingChallenge | null>(null);
const [mobileBusy, setMobileBusy] = createSignal(false);
const [mobileError, setMobileError] = createSignal<string | null>(null);

// Raw ironclad fleet status snapshot + settings, fetched via the bridge. Kept
// as opaque records — the fleet matrix derives its rows / connection metadata
// from these with the pure helpers in `machines/fleetWiring` (Req 8.1).
const [ironcladStatus, setIroncladStatus] = createSignal<unknown | null>(null);
const [settings, setSettings] = createSignal<unknown | null>(null);

// ─── Actions ───────────────────────────────────────────────────────────────────

/**
 * Load the fleet status snapshot + settings through the bridge (existing
 * `get_ironclad_status` / `get_settings` commands). Never throws — when the
 * fleet service is absent the snapshot stays null and the matrix degrades to
 * honest empty/idle states (Req 20.4).
 */
async function loadFleetStatus(): Promise<void> {
  const [statusRes, settingsRes] = await Promise.all([
    bridgeInvoke<unknown>("get_ironclad_status"),
    bridgeInvoke<unknown>("get_settings"),
  ]);
  if (statusRes.ok) setIroncladStatus(statusRes.data);
  if (settingsRes.ok) setSettings(settingsRes.data);
}

/**
 * Dispatch enrollment through the runtime's EXISTING `register_new_target`
 * command (dispatch-only — the runtime performs SSH bootstrap + host-key
 * verification). Refreshes the snapshot on success. Returns the typed
 * ServiceResult so the caller can surface honest success/error states.
 */
async function enrollTarget<T = unknown>(
  request: EnrollTargetRequest,
): Promise<ServiceResult<T>> {
  const res = await bridgeInvoke<T>("register_new_target", { request });
  if (res.ok) void loadFleetStatus();
  return res;
}

/**
 * Dispatch a destructive delete through the runtime's EXISTING `delete_target`
 * command. The caller is responsible for the deliberate confirm (Req 8.4).
 */
async function deleteTargetById<T = unknown>(targetId: string): Promise<ServiceResult<T>> {
  const res = await bridgeInvoke<T>("delete_target", { targetId });
  if (res.ok) void loadFleetStatus();
  return res;
}

function updateDeviceStatus(deviceId: string, status: DeviceStatus): void {
  setDevices((prev) => prev.map((d) => (d.id === deviceId ? { ...d, status } : d)));
  eventBus.emit("machine:status-changed", { deviceId, status });
}

function addDevice(device: Device): void {
  setDevices((prev) => [...prev.filter((d) => d.id !== device.id), device]);
  eventBus.emit("machine:enrolled", { deviceId: device.id });
}

function removeDevice(deviceId: string): void {
  setDevices((prev) => prev.filter((d) => d.id !== deviceId));
}

function startRemoteSession(deviceId: string): void {
  setActiveRemoteSession({ deviceId, active: true });
}

function endRemoteSession(): void {
  setActiveRemoteSession(null);
}

/**
 * Read the authoritative capture/input lifecycle from the desktop runtime.
 * No status is inferred from the browser transport: unavailable stays explicit.
 */
async function loadRemoteDesktopStatus(): Promise<ServiceResult<RemoteDesktopStatus>> {
  const result = await bridgeInvoke<RemoteDesktopStatus>("remote_desktop_status");
  if (result.ok) {
    setRemoteDesktopStatus((previous) =>
      sameRemoteDesktopStatus(previous, result.data) ? previous : result.data,
    );
    setRemoteDesktopError(null);
  } else {
    setRemoteDesktopError(result.message);
  }
  return result;
}

/** One-action emergency stop through KRIA's existing idempotent kill command. */
async function killRemoteDesktop(): Promise<ServiceResult<void>> {
  setRemoteDesktopBusy(true);
  const result = await bridgeInvoke<void>("remote_desktop_kill");
  setRemoteDesktopBusy(false);
  if (result.ok) {
    setRemoteDesktopStatus((previous) =>
      previous
        ? {
            ...previous,
            state: "stopped",
            session_id: null,
            started_at: null,
            last_activity: null,
            running: false,
          }
        : null,
    );
    setRemoteDesktopError(null);
    endRemoteSession();
  } else {
    setRemoteDesktopError(result.message);
  }
  return result;
}

/**
 * Refresh gateway + paired devices through KRIA's runtime commands. Calls are
 * parallel and bounded by bridge timeouts; partial success remains visible.
 */
async function loadMobileState(): Promise<void> {
  const [statusResult, devicesResult] = await Promise.all([
    bridgeInvoke<MobileGatewayStatus>("mobile_gateway_status"),
    bridgeInvoke<{ devices: MobileDeviceInfo[] }>("mobile_list_devices"),
  ]);

  if (statusResult.ok) {
    setMobileGatewayStatus((previous) =>
      sameMobileGatewayStatus(previous, statusResult.data) ? previous : statusResult.data,
    );
  }
  if (devicesResult.ok) {
    const nextDevices = devicesResult.data.devices ?? [];
    setMobileDevices((previous) => sameMobileDevices(previous, nextDevices) ? previous : nextDevices);
  }

  const failure = !statusResult.ok ? statusResult : !devicesResult.ok ? devicesResult : null;
  setMobileError(failure ? failure.message : null);
}

async function startMobileGateway(): Promise<ServiceResult<unknown>> {
  setMobileBusy(true);
  const result = await bridgeInvoke<unknown>("mobile_gateway_start");
  if (result.ok) {
    setMobileError(null);
    await loadMobileState();
  } else {
    setMobileError(result.message);
  }
  setMobileBusy(false);
  return result;
}

async function stopMobileGateway(): Promise<ServiceResult<void>> {
  setMobileBusy(true);
  const result = await bridgeInvoke<void>("mobile_gateway_stop");
  if (result.ok) {
    setMobilePairing(null);
    setMobileError(null);
    await loadMobileState();
  } else {
    setMobileError(result.message);
  }
  setMobileBusy(false);
  return result;
}

async function beginMobilePairing(): Promise<ServiceResult<MobilePairingChallenge>> {
  setMobileBusy(true);
  const result = await bridgeInvoke<MobilePairingChallenge>("mobile_begin_pairing");
  if (result.ok) {
    setMobilePairing(result.data);
    setMobileError(null);
  } else {
    setMobileError(result.message);
  }
  setMobileBusy(false);
  return result;
}

/** Destructive token revocation; caller must obtain deliberate confirmation. */
async function revokeMobileDevice(
  deviceId: string,
): Promise<ServiceResult<{ device_id: string; revoked: boolean }>> {
  setMobileBusy(true);
  const result = await bridgeInvoke<{ device_id: string; revoked: boolean }>(
    "mobile_revoke_device",
    { deviceId },
  );
  if (result.ok) {
    setMobileDevices((previous) =>
      previous.map((device) =>
        device.id === deviceId ? { ...device, revoked: true } : device,
      ),
    );
    setMobileError(null);
  } else {
    setMobileError(result.message);
  }
  setMobileBusy(false);
  return result;
}

function resetMobileState(): void {
  setMobileGatewayStatus(null);
  setMobileDevices([]);
  setMobilePairing(null);
  setMobileBusy(false);
  setMobileError(null);
}

// ─── Export ────────────────────────────────────────────────────────────────────

export const machineStore = {
  devices,
  activeRemoteSession,
  remoteDesktopStatus,
  remoteDesktopError,
  remoteDesktopBusy,
  enrollmentPending,
  ironcladStatus,
  settings,
  mobileGatewayStatus,
  mobileDevices,
  mobilePairing,
  mobileBusy,
  mobileError,

  setDevices,
  setRemoteDesktopStatus,
  setRemoteDesktopError,
  setEnrollmentPending,
  setIroncladStatus,
  setSettings,
  setMobileGatewayStatus,
  setMobileDevices,
  setMobilePairing,
  setMobileError,
  loadFleetStatus,
  loadRemoteDesktopStatus,
  killRemoteDesktop,
  loadMobileState,
  startMobileGateway,
  stopMobileGateway,
  beginMobilePairing,
  revokeMobileDevice,
  resetMobileState,
  enrollTarget,
  deleteTargetById,
  updateDeviceStatus,
  addDevice,
  removeDevice,
  startRemoteSession,
  endRemoteSession,
} as const;
