/**
 * Icon — references a symbol in the bundled Lucide SVG sprite (design.md §1.15).
 *
 * The sprite (`public/icons/lucide-sprite.svg`) is generated by
 * `npm run icons:build` from scripts/icon-manifest.json. Rendering via <use>
 * gives zero per-icon runtime cost and one consistent stroke weight. Color
 * follows `currentColor`; size is controlled by the `size` prop (defaults to
 * 1em so icons scale with surrounding text).
 *
 * Icons are decorative by default (aria-hidden). Pass a `title` to expose an
 * accessible name (Req 17: never convey meaning by icon alone — pair with text
 * in the surrounding control, or set `title` when the icon stands alone).
 *
 * Add new icons: append the kebab-case Lucide name to scripts/icon-manifest.json
 * and re-run `npm run icons:build`. Emoji is reserved for user content only.
 */
import { splitProps, type JSX } from "solid-js";

const SPRITE_URL = "/icons/lucide-sprite.svg";

export interface IconProps extends JSX.SvgSVGAttributes<SVGSVGElement> {
  /** Lucide icon id (kebab-case) present in the sprite. */
  name: string;
  /** Size in px or any CSS length. Defaults to "1em" (scales with text). */
  size?: number | string;
  /** Accessible name. When omitted the icon is aria-hidden (decorative). */
  title?: string;
}

export function Icon(props: IconProps) {
  const [local, rest] = splitProps(props, ["name", "size", "title", "class"]);
  const size = () => (local.size == null ? "1em" : typeof local.size === "number" ? `${local.size}px` : local.size);

  return (
    <svg
      class={local.class}
      width={size()}
      height={size()}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden={local.title ? undefined : "true"}
      role={local.title ? "img" : undefined}
      aria-label={local.title}
      {...rest}
    >
      {local.title ? <title>{local.title}</title> : null}
      <use href={`${SPRITE_URL}#${local.name}`} />
    </svg>
  );
}

export default Icon;
