/**
 * Icon — references a symbol in the bundled Lucide SVG sprite (design.md §1.15).
 *
 * The sprite (`public/icons/lucide-sprite.svg`) is generated by
 * `npm run icons:build` from scripts/icon-manifest.json. Rendering via <use>
 * gives zero per-icon runtime cost and one consistent stroke weight. Color
 * follows `currentColor`; size is controlled by the `size` prop (defaults to
 * 1em so icons scale with surrounding text).
 *
 * Icons are decorative by default (aria-hidden). Pass a `title` to expose an
 * accessible name (Req 17: never convey meaning by icon alone — pair with text
 * in the surrounding control, or set `title` when the icon stands alone).
 *
 * Add new icons: append the kebab-case Lucide name to scripts/icon-manifest.json
 * and re-run `npm run icons:build`. Emoji is reserved for user content only.
 */
import { splitProps, type JSX } from "solid-js";

const SPRITE_URL = "/icons/lucide-sprite.svg";

/**
 * Named icon sizes tied to the type scale (tokens.generated.css / type.json),
 * so explicit sizes reference a documented role instead of an ad-hoc pixel
 * value (design.md §13; task 13.3). Prefer these — or the default 1em, which
 * inherits the surrounding control's tokenized font-size — over raw numbers.
 */
export type IconSizeRole = "micro" | "caption" | "body" | "heading" | "title" | "display";

const SIZE_ROLE_TOKENS: Record<IconSizeRole, string> = {
  micro: "var(--font-size-micro)",
  caption: "var(--font-size-caption)",
  body: "var(--font-size-body)",
  heading: "var(--font-size-heading)",
  title: "var(--font-size-title)",
  display: "var(--font-size-display)",
};

export interface IconProps extends JSX.SvgSVGAttributes<SVGSVGElement> {
  /** Lucide icon id (kebab-case) present in the sprite. */
  name: string;
  /**
   * Icon size. Prefer a type-scale role ("caption" | "body" | "heading" | …)
   * so the size maps to the token scale; a number is treated as px and any
   * other CSS length is passed through. Defaults to "1em" (scales with the
   * surrounding text / control font-size).
   */
  size?: number | IconSizeRole | (string & {});
  /** Accessible name. When omitted the icon is aria-hidden (decorative). */
  title?: string;
}

function resolveSize(size: IconProps["size"]): string {
  if (size == null) return "1em";
  if (typeof size === "number") return `${size}px`;
  if (size in SIZE_ROLE_TOKENS) return SIZE_ROLE_TOKENS[size as IconSizeRole];
  return size;
}

export function Icon(props: IconProps) {
  const [local, rest] = splitProps(props, ["name", "size", "title", "class"]);
  const size = () => resolveSize(local.size);

  return (
    <svg
      class={local.class}
      width={size()}
      height={size()}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden={local.title ? undefined : "true"}
      role={local.title ? "img" : undefined}
      aria-label={local.title}
      {...rest}
    >
      {local.title ? <title>{local.title}</title> : null}
      <use href={`${SPRITE_URL}#${local.name}`} />
    </svg>
  );
}

export default Icon;
