use std::collections::HashSet;

use chrono::{DateTime, Utc};

use crate::memory::semantic_parser::MemoryExtraction;
use crate::memory::store::{
    ChatMediaRecord, ConversationTurn, DocumentChunk, MemoryFact, MemoryFetchRequest, MemoryStore,
    PreferenceRecord,
};

/// Typed write request for persisting one complete conversational exchange and
/// any semantic extraction generated by higher layers.
#[derive(Debug, Clone)]
pub struct MemoryTurnWrite {
    pub session_id: String,
    pub user_prompt: String,
    pub assistant_response: String,
    pub tool_name: Option<String>,
    pub tool_result: Option<String>,
    pub tokens_used: Option<i32>,
    pub timestamp: DateTime<Utc>,
    pub extraction: Option<MemoryExtraction>,
}

/// Semantic write authority boundary for memory persistence.
///
/// During migration, `MemoryStore` implements this trait directly so existing
/// callers can progressively move from store-specific writes to this contract.
pub trait MemoryManager: Send + Sync {
    fn store_turn(&self, turn: &MemoryTurnWrite) -> anyhow::Result<i64>;
    fn delete_session(&self, session_id: &str) -> anyhow::Result<usize>;
    fn delete_session_preferences(&self, session_id: &str) -> anyhow::Result<usize>;
    fn store_fact(&self, fact: &MemoryFact) -> anyhow::Result<i64>;
    fn update_fact_access(&self, id: i64) -> anyhow::Result<()>;
    fn update_fact_decay(&self, id: i64, new_score: f64) -> anyhow::Result<()>;
    fn delete_fact(&self, id: i64) -> anyhow::Result<()>;
    fn store_media(&self, media: &ChatMediaRecord) -> anyhow::Result<i64>;
    fn store_snippet(
        &self,
        name: &str,
        content: &str,
        language: &str,
        tags: &[String],
    ) -> anyhow::Result<()>;
    fn store_document_chunk(&self, chunk: &DocumentChunk) -> anyhow::Result<i64>;
    fn delete_document_chunks(&self, doc_id: &str) -> anyhow::Result<usize>;
    fn set_preference(&self, preference: &PreferenceRecord) -> anyhow::Result<()>;
}

/// Semantic read authority boundary for runtime callers.
///
/// Runtime layers (desktop/telegram/tools) should read through this trait
/// rather than depending on concrete persistence internals.
pub trait MemoryReader: Send + Sync {
    fn fetch_memories(&self, query: &MemoryFetchRequest) -> anyhow::Result<Vec<ConversationTurn>>;
    fn get_recent_turns(
        &self,
        session_id: &str,
        limit: usize,
    ) -> anyhow::Result<Vec<ConversationTurn>>;
    fn search_conversations(
        &self,
        query: &str,
        limit: usize,
    ) -> anyhow::Result<Vec<ConversationTurn>>;
    fn search_facts(&self, query: &str, limit: usize) -> anyhow::Result<Vec<MemoryFact>>;
    fn all_facts_with_decay(&self, min_score: f64) -> anyhow::Result<Vec<MemoryFact>>;
    fn get_preference(&self, key: &str) -> anyhow::Result<Option<String>>;
    fn list_sessions(&self) -> anyhow::Result<Vec<(String, i64, String)>>;
    fn list_documents(&self) -> anyhow::Result<Vec<(String, String, String, i64)>>;
    fn get_session_media(&self, session_id: &str) -> anyhow::Result<Vec<ChatMediaRecord>>;
    fn get_snippet(&self, name: &str) -> anyhow::Result<Option<(String, String, String)>>;
    fn list_snippets(&self, tag: Option<&str>) -> anyhow::Result<Vec<String>>;
}

/// Unified runtime-facing memory contract.
pub trait MemoryRuntime: MemoryManager + MemoryReader {}

impl<T> MemoryRuntime for T where T: MemoryManager + MemoryReader + ?Sized {}

impl MemoryManager for MemoryStore {
    fn store_turn(&self, turn: &MemoryTurnWrite) -> anyhow::Result<i64> {
        let mut last_stored_turn_id = 0_i64;

        if !turn.user_prompt.trim().is_empty() {
            let user_turn = ConversationTurn {
                id: None,
                session_id: turn.session_id.clone(),
                role: "user".to_string(),
                content: turn.user_prompt.clone(),
                tool_name: None,
                tool_result: None,
                tokens_used: None,
                timestamp: turn.timestamp,
            };
            last_stored_turn_id = MemoryStore::store_turn(self, &user_turn)?;
        }

        let has_assistant_payload = !turn.assistant_response.trim().is_empty()
            || turn
                .tool_name
                .as_deref()
                .is_some_and(|name| !name.trim().is_empty())
            || turn
                .tool_result
                .as_deref()
                .is_some_and(|result| !result.trim().is_empty())
            || turn.tokens_used.is_some();

        if has_assistant_payload {
            let assistant_turn = ConversationTurn {
                id: None,
                session_id: turn.session_id.clone(),
                role: "assistant".to_string(),
                content: turn.assistant_response.clone(),
                tool_name: turn.tool_name.clone(),
                tool_result: turn.tool_result.clone(),
                tokens_used: turn.tokens_used,
                timestamp: turn.timestamp,
            };
            last_stored_turn_id = MemoryStore::store_turn(self, &assistant_turn)?;
        }

        if let Some(extraction) = turn.extraction.as_ref() {
            let mut seen = HashSet::new();

            for text in extraction
                .extracted_facts
                .iter()
                .map(|fact| fact.trim())
                .filter(|fact| !fact.is_empty())
            {
                if !seen.insert(text.to_string()) {
                    continue;
                }

                let fact = MemoryFact {
                    id: None,
                    text: text.to_string(),
                    category: "semantic_fact".to_string(),
                    source: "semantic_parser".to_string(),
                    created_at: turn.timestamp,
                    last_accessed: turn.timestamp,
                    access_count: 0,
                    decay_score: 1.0,
                };
                let _ = MemoryStore::store_fact(self, &fact)?;
            }

            let inferred_context = extraction.inferred_context.trim();
            if !inferred_context.is_empty() && seen.insert(inferred_context.to_string()) {
                let context_fact = MemoryFact {
                    id: None,
                    text: inferred_context.to_string(),
                    category: "inferred_context".to_string(),
                    source: "semantic_parser".to_string(),
                    created_at: turn.timestamp,
                    last_accessed: turn.timestamp,
                    access_count: 0,
                    decay_score: 1.0,
                };
                let _ = MemoryStore::store_fact(self, &context_fact)?;
            }

            for (key, value) in &extraction.user_preferences {
                let key = key.trim();
                let value = value.trim();
                if key.is_empty() || value.is_empty() {
                    continue;
                }
                MemoryStore::set_preference_record(
                    self,
                    &PreferenceRecord {
                        key: key.to_string(),
                        value: value.to_string(),
                    },
                )?;
            }
        }

        Ok(last_stored_turn_id)
    }

    fn delete_session(&self, session_id: &str) -> anyhow::Result<usize> {
        MemoryStore::delete_session(self, session_id)
    }

    fn delete_session_preferences(&self, session_id: &str) -> anyhow::Result<usize> {
        MemoryStore::delete_session_preferences(self, session_id)
    }

    fn store_fact(&self, fact: &MemoryFact) -> anyhow::Result<i64> {
        MemoryStore::store_fact(self, fact)
    }

    fn update_fact_access(&self, id: i64) -> anyhow::Result<()> {
        MemoryStore::update_fact_access(self, id)
    }

    fn update_fact_decay(&self, id: i64, new_score: f64) -> anyhow::Result<()> {
        MemoryStore::update_fact_decay(self, id, new_score)
    }

    fn delete_fact(&self, id: i64) -> anyhow::Result<()> {
        MemoryStore::delete_fact(self, id)
    }

    fn store_media(&self, media: &ChatMediaRecord) -> anyhow::Result<i64> {
        MemoryStore::store_chat_media(self, media)
    }

    fn store_snippet(
        &self,
        name: &str,
        content: &str,
        language: &str,
        tags: &[String],
    ) -> anyhow::Result<()> {
        MemoryStore::save_snippet(self, name, content, language, tags)
    }

    fn store_document_chunk(&self, chunk: &DocumentChunk) -> anyhow::Result<i64> {
        MemoryStore::store_chunk(self, chunk)
    }

    fn delete_document_chunks(&self, doc_id: &str) -> anyhow::Result<usize> {
        MemoryStore::delete_document_chunks(self, doc_id)
    }

    fn set_preference(&self, preference: &PreferenceRecord) -> anyhow::Result<()> {
        MemoryStore::set_preference_record(self, preference)
    }
}

impl MemoryReader for MemoryStore {
    fn fetch_memories(&self, query: &MemoryFetchRequest) -> anyhow::Result<Vec<ConversationTurn>> {
        MemoryStore::fetch_memories(self, query)
    }

    fn get_recent_turns(
        &self,
        session_id: &str,
        limit: usize,
    ) -> anyhow::Result<Vec<ConversationTurn>> {
        MemoryStore::get_recent_turns(self, session_id, limit)
    }

    fn search_conversations(
        &self,
        query: &str,
        limit: usize,
    ) -> anyhow::Result<Vec<ConversationTurn>> {
        MemoryStore::search_conversations(self, query, limit)
    }

    fn search_facts(&self, query: &str, limit: usize) -> anyhow::Result<Vec<MemoryFact>> {
        MemoryStore::search_facts(self, query, limit)
    }

    fn all_facts_with_decay(&self, min_score: f64) -> anyhow::Result<Vec<MemoryFact>> {
        MemoryStore::all_facts_with_decay(self, min_score)
    }

    fn get_preference(&self, key: &str) -> anyhow::Result<Option<String>> {
        MemoryStore::get_preference(self, key)
    }

    fn list_sessions(&self) -> anyhow::Result<Vec<(String, i64, String)>> {
        MemoryStore::list_sessions(self)
    }

    fn list_documents(&self) -> anyhow::Result<Vec<(String, String, String, i64)>> {
        MemoryStore::list_documents(self)
    }

    fn get_session_media(&self, session_id: &str) -> anyhow::Result<Vec<ChatMediaRecord>> {
        MemoryStore::get_session_media(self, session_id)
    }

    fn get_snippet(&self, name: &str) -> anyhow::Result<Option<(String, String, String)>> {
        MemoryStore::get_snippet(self, name)
    }

    fn list_snippets(&self, tag: Option<&str>) -> anyhow::Result<Vec<String>> {
        MemoryStore::list_snippets(self, tag)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn assert_memory_manager_impl<T: MemoryManager>() {}
    fn assert_memory_reader_impl<T: MemoryReader>() {}
    fn assert_memory_runtime_impl<T: MemoryRuntime>() {}

    #[test]
    fn memory_store_implements_memory_manager() {
        assert_memory_manager_impl::<MemoryStore>();
        assert_memory_reader_impl::<MemoryStore>();
        assert_memory_runtime_impl::<MemoryStore>();
    }
}
