"""Correct the audio handler file to the real domain API."""

import pathlib

p = pathlib.Path("/media/obaid/SSD/KRIA/crates/kria-core/src/tools/audio.rs")
s = p.read_text(encoding="utf-8")

# 1. Imports: the id newtypes live in audio/mod.rs (generated by `audio_id!`).
s = s.replace(
    """use crate::os_control::audio::media::{MediaPlaybackAction, MediaPlayerId, MediaRequest};
use crate::os_control::audio::streams::{
    AudioStreamId, AudioStreamOp, AudioStreamRequest, StreamFocus,
};
use crate::os_control::audio::{
    AudioEndpointId, AudioEndpointKind, AudioOp, AudioProfileId, AudioRequest,
};""",
    """use crate::os_control::audio::media::{MediaPlaybackAction, MediaRequest};
use crate::os_control::audio::streams::{AudioStreamOp, AudioStreamRequest};
use crate::os_control::audio::{
    AudioEndpointId, AudioEndpointKind, AudioOp, AudioProfileId, AudioRequest, AudioStreamId,
};""",
)

# 2. Ids are validated on construction with `parse`, not `new`.
s = s.replace(
    "AudioOp::SetDefaultEndpoint(AudioEndpointId::new(device)),",
    """AudioOp::SetDefaultEndpoint(match AudioEndpointId::parse(&device) {
                Ok(id) => id,
                Err(error) => return gov::os_error(&error),
            }),""",
)
s = s.replace(
    """            AudioOp::SetProfile {
                endpoint: AudioEndpointId::new(device),
                profile: AudioProfileId::new(profile),""",
    """            AudioOp::SetProfile {
                endpoint: match AudioEndpointId::parse(&device) {
                    Ok(id) => id,
                    Err(error) => return gov::os_error(&error),
                },
                profile: match AudioProfileId::parse(&profile) {
                    Ok(id) => id,
                    Err(error) => return gov::os_error(&error),
                },""",
)

# 3. AudioStreamRequest has no `focus` field; the op carries the intent.
s = s.replace(
    """    stream: AudioStreamId,
    op: AudioStreamOp,
    focus: StreamFocus,
) -> ToolResult {""",
    """    stream: AudioStreamId,
    op: AudioStreamOp,
) -> ToolResult {""",
)
s = s.replace(
    """        stream,
        op,
        focus,
    };""",
    """        stream,
        op,
    };""",
)
for call in (
    """            AudioStreamId::new(stream),
            AudioStreamOp::SetLevel(level),
            StreamFocus::Level,
        )""",
    """            AudioStreamId::new(stream),
            AudioStreamOp::SetMute(muted),
            StreamFocus::Mute,
        )""",
):
    op = "SetLevel(level)" if "SetLevel" in call else "SetMute(muted)"
    s = s.replace(
        call,
        f"""            match AudioStreamId::parse(&stream) {{
                Ok(id) => id,
                Err(error) => return gov::os_error(&error),
            }},
            AudioStreamOp::{op},
        )""",
    )

# 4. `AudioRequest::desired_state()` is Option: a mutation must have one.
s = s.replace(
    """    let desired = request.desired_state();
    let plan = gov::plan_for(resolved.provider_id, request.comparator(), request.tolerance());
    gov::run_mutation(
        tool,
        &resolved.runtime,
        provider,
        &call,
        &request,
        &desired,
        &plan,
    )
    .await
}

struct SetMicrophoneLevel;""",
    """    // A mutation always has a desired state; `None` would mean this op is a read,
    // which must never reach the mutation path.
    let Some(desired) = request.desired_state() else {
        return ToolResult::err(format!(
            "`{tool}` has no desired state and cannot be applied as a mutation"
        ));
    };
    let plan = gov::plan_for(resolved.provider_id, request.comparator(), request.tolerance());
    gov::run_mutation(
        tool,
        &resolved.runtime,
        provider,
        &call,
        &request,
        &desired,
        &plan,
    )
    .await
}

struct SetMicrophoneLevel;""",
)

p.write_text(s, encoding="utf-8")
print("audio handler API corrected")
