use chrono::{DateTime, Utc};

use crate::runtime_types::{
    ChatMediaRecord, ConversationTurn, DocumentChunk, MemoryFact, MemoryFetchRequest,
    PreferenceRecord,
};
use crate::semantic_parser::MemoryExtraction;

/// Typed write request for persisting one complete conversational exchange and
/// any semantic extraction generated by higher layers.
#[derive(Debug, Clone)]
pub struct MemoryTurnWrite {
    pub session_id: String,
    pub user_prompt: String,
    pub assistant_response: String,
    pub tool_name: Option<String>,
    pub tool_result: Option<String>,
    pub tokens_used: Option<i32>,
    pub timestamp: DateTime<Utc>,
    pub extraction: Option<MemoryExtraction>,
}

/// Semantic write authority boundary for memory persistence.
///
/// The production implementor is
/// [`crate::runtime_backend::KriaMemoryRuntime`], backed by the single
/// authority database.
pub trait MemoryManager: Send + Sync {
    fn store_turn(&self, turn: &MemoryTurnWrite) -> anyhow::Result<i64>;
    fn delete_session(&self, session_id: &str) -> anyhow::Result<usize>;
    fn delete_session_preferences(&self, session_id: &str) -> anyhow::Result<usize>;
    fn store_fact(&self, fact: &MemoryFact) -> anyhow::Result<i64>;
    fn update_fact_access(&self, id: i64) -> anyhow::Result<()>;
    fn update_fact_decay(&self, id: i64, new_score: f64) -> anyhow::Result<()>;
    fn delete_fact(&self, id: i64) -> anyhow::Result<()>;
    fn store_media(&self, media: &ChatMediaRecord) -> anyhow::Result<i64>;
    fn store_snippet(
        &self,
        name: &str,
        content: &str,
        language: &str,
        tags: &[String],
    ) -> anyhow::Result<()>;
    fn store_document_chunk(&self, chunk: &DocumentChunk) -> anyhow::Result<i64>;
    fn delete_document_chunks(&self, doc_id: &str) -> anyhow::Result<usize>;
    fn set_preference(&self, preference: &PreferenceRecord) -> anyhow::Result<()>;
}

/// Semantic read authority boundary for runtime callers.
///
/// Runtime layers (desktop/telegram/tools) read through this trait rather than
/// depending on concrete persistence internals.
pub trait MemoryReader: Send + Sync {
    fn fetch_memories(&self, query: &MemoryFetchRequest) -> anyhow::Result<Vec<ConversationTurn>>;
    fn get_recent_turns(
        &self,
        session_id: &str,
        limit: usize,
    ) -> anyhow::Result<Vec<ConversationTurn>>;
    /// Every turn in a session, oldest first — for export, where a `limit` would
    /// silently drop the start of a long conversation.
    fn get_all_turns(&self, session_id: &str) -> anyhow::Result<Vec<ConversationTurn>>;
    fn search_conversations(
        &self,
        query: &str,
        limit: usize,
    ) -> anyhow::Result<Vec<ConversationTurn>>;
    fn search_facts(&self, query: &str, limit: usize) -> anyhow::Result<Vec<MemoryFact>>;
    fn all_facts_with_decay(&self, min_score: f64) -> anyhow::Result<Vec<MemoryFact>>;
    fn get_preference(&self, key: &str) -> anyhow::Result<Option<String>>;
    fn list_sessions(&self) -> anyhow::Result<Vec<(String, i64, String)>>;
    fn list_documents(&self) -> anyhow::Result<Vec<(String, String, String, i64)>>;
    fn get_session_media(&self, session_id: &str) -> anyhow::Result<Vec<ChatMediaRecord>>;
    fn get_snippet(&self, name: &str) -> anyhow::Result<Option<(String, String, String)>>;
    fn list_snippets(&self, tag: Option<&str>) -> anyhow::Result<Vec<String>>;
}

/// Unified runtime-facing memory contract.
pub trait MemoryRuntime: MemoryManager + MemoryReader {}

impl<T> MemoryRuntime for T where T: MemoryManager + MemoryReader + ?Sized {}
