import type { Meta, StoryObj } from "storybook-solidjs-vite";
import { ProvenanceCue } from "./ProvenanceCue";

const meta = {
  title: "Kit/ProvenanceCue",
  component: ProvenanceCue,
} satisfies Meta<typeof ProvenanceCue>;

export default meta;
type Story = StoryObj<typeof meta>;

export const KriaAuthored: Story = { args: { source: "kria", label: "Generated by KRIA" } };
export const UserAuthored: Story = { args: { source: "user" } };
